// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: okk.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyComparisonType int32

const (
	KeyComparisonType_EQUAL   KeyComparisonType = 0
	KeyComparisonType_FLOOR   KeyComparisonType = 1
	KeyComparisonType_CEILING KeyComparisonType = 2
	KeyComparisonType_LOWER   KeyComparisonType = 3
	KeyComparisonType_HIGHER  KeyComparisonType = 4
)

// Enum value maps for KeyComparisonType.
var (
	KeyComparisonType_name = map[int32]string{
		0: "EQUAL",
		1: "FLOOR",
		2: "CEILING",
		3: "LOWER",
		4: "HIGHER",
	}
	KeyComparisonType_value = map[string]int32{
		"EQUAL":   0,
		"FLOOR":   1,
		"CEILING": 2,
		"LOWER":   3,
		"HIGHER":  4,
	}
)

func (x KeyComparisonType) Enum() *KeyComparisonType {
	p := new(KeyComparisonType)
	*p = x
	return p
}

func (x KeyComparisonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyComparisonType) Descriptor() protoreflect.EnumDescriptor {
	return file_okk_proto_enumTypes[0].Descriptor()
}

func (KeyComparisonType) Type() protoreflect.EnumType {
	return &file_okk_proto_enumTypes[0]
}

func (x KeyComparisonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyComparisonType.Descriptor instead.
func (KeyComparisonType) EnumDescriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{0}
}

type NotificationType int32

const (
	NotificationType_KEY_CREATED       NotificationType = 0
	NotificationType_KEY_MODIFIED      NotificationType = 1
	NotificationType_KEY_DELETED       NotificationType = 2
	NotificationType_KEY_RANGE_DELETED NotificationType = 3
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "KEY_CREATED",
		1: "KEY_MODIFIED",
		2: "KEY_DELETED",
		3: "KEY_RANGE_DELETED",
	}
	NotificationType_value = map[string]int32{
		"KEY_CREATED":       0,
		"KEY_MODIFIED":      1,
		"KEY_DELETED":       2,
		"KEY_RANGE_DELETED": 3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_okk_proto_enumTypes[1].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_okk_proto_enumTypes[1]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_Ok                  Status = 0
	Status_AssertionFailure    Status = 1
	Status_RetryableFailure    Status = 2
	Status_NonRetryableFailure Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Ok",
		1: "AssertionFailure",
		2: "RetryableFailure",
		3: "NonRetryableFailure",
	}
	Status_value = map[string]int32{
		"Ok":                  0,
		"AssertionFailure":    1,
		"RetryableFailure":    2,
		"NonRetryableFailure": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_okk_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_okk_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{2}
}

type OperationSessionRestart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationSessionRestart) Reset() {
	*x = OperationSessionRestart{}
	mi := &file_okk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationSessionRestart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationSessionRestart) ProtoMessage() {}

func (x *OperationSessionRestart) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationSessionRestart.ProtoReflect.Descriptor instead.
func (*OperationSessionRestart) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{0}
}

type OperationPut struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value            []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ephemeral        bool                   `protobuf:"varint,3,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	PartitionKey     *string                `protobuf:"bytes,4,opt,name=partition_key,json=partitionKey,proto3,oneof" json:"partition_key,omitempty"`
	SequenceKeyDelta []uint64               `protobuf:"varint,5,rep,packed,name=sequence_key_delta,json=sequenceKeyDelta,proto3" json:"sequence_key_delta,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperationPut) Reset() {
	*x = OperationPut{}
	mi := &file_okk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationPut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationPut) ProtoMessage() {}

func (x *OperationPut) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationPut.ProtoReflect.Descriptor instead.
func (*OperationPut) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{1}
}

func (x *OperationPut) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OperationPut) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OperationPut) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *OperationPut) GetPartitionKey() string {
	if x != nil && x.PartitionKey != nil {
		return *x.PartitionKey
	}
	return ""
}

func (x *OperationPut) GetSequenceKeyDelta() []uint64 {
	if x != nil {
		return x.SequenceKeyDelta
	}
	return nil
}

type OperationGet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ComparisonType KeyComparisonType      `protobuf:"varint,2,opt,name=comparison_type,json=comparisonType,proto3,enum=io.oxia.okk.proto.v1.KeyComparisonType" json:"comparison_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationGet) Reset() {
	*x = OperationGet{}
	mi := &file_okk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationGet) ProtoMessage() {}

func (x *OperationGet) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationGet.ProtoReflect.Descriptor instead.
func (*OperationGet) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{2}
}

func (x *OperationGet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OperationGet) GetComparisonType() KeyComparisonType {
	if x != nil {
		return x.ComparisonType
	}
	return KeyComparisonType_EQUAL
}

type OperationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyStart      string                 `protobuf:"bytes,1,opt,name=key_start,json=keyStart,proto3" json:"key_start,omitempty"`
	KeyEnd        string                 `protobuf:"bytes,2,opt,name=key_end,json=keyEnd,proto3" json:"key_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationList) Reset() {
	*x = OperationList{}
	mi := &file_okk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationList) ProtoMessage() {}

func (x *OperationList) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationList.ProtoReflect.Descriptor instead.
func (*OperationList) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{3}
}

func (x *OperationList) GetKeyStart() string {
	if x != nil {
		return x.KeyStart
	}
	return ""
}

func (x *OperationList) GetKeyEnd() string {
	if x != nil {
		return x.KeyEnd
	}
	return ""
}

type OperationScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyStart      string                 `protobuf:"bytes,1,opt,name=key_start,json=keyStart,proto3" json:"key_start,omitempty"`
	KeyEnd        string                 `protobuf:"bytes,2,opt,name=key_end,json=keyEnd,proto3" json:"key_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationScan) Reset() {
	*x = OperationScan{}
	mi := &file_okk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationScan) ProtoMessage() {}

func (x *OperationScan) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationScan.ProtoReflect.Descriptor instead.
func (*OperationScan) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{4}
}

func (x *OperationScan) GetKeyStart() string {
	if x != nil {
		return x.KeyStart
	}
	return ""
}

func (x *OperationScan) GetKeyEnd() string {
	if x != nil {
		return x.KeyEnd
	}
	return ""
}

type OperationDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationDelete) Reset() {
	*x = OperationDelete{}
	mi := &file_okk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDelete) ProtoMessage() {}

func (x *OperationDelete) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDelete.ProtoReflect.Descriptor instead.
func (*OperationDelete) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{5}
}

func (x *OperationDelete) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OperationDeleteRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyStart      string                 `protobuf:"bytes,1,opt,name=key_start,json=keyStart,proto3" json:"key_start,omitempty"`
	KeyEnd        string                 `protobuf:"bytes,2,opt,name=key_end,json=keyEnd,proto3" json:"key_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationDeleteRange) Reset() {
	*x = OperationDeleteRange{}
	mi := &file_okk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationDeleteRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDeleteRange) ProtoMessage() {}

func (x *OperationDeleteRange) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDeleteRange.ProtoReflect.Descriptor instead.
func (*OperationDeleteRange) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{6}
}

func (x *OperationDeleteRange) GetKeyStart() string {
	if x != nil {
		return x.KeyStart
	}
	return ""
}

func (x *OperationDeleteRange) GetKeyEnd() string {
	if x != nil {
		return x.KeyEnd
	}
	return ""
}

type Operation struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Sequence     int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Assertion    *Assertion             `protobuf:"bytes,2,opt,name=assertion,proto3,oneof" json:"assertion,omitempty"`
	Precondition *Precondition          `protobuf:"bytes,3,opt,name=precondition,proto3,oneof" json:"precondition,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Operation_Put
	//	*Operation_Delete
	//	*Operation_Get
	//	*Operation_List
	//	*Operation_Scan
	//	*Operation_SessionRestart
	//	*Operation_DeleteRange
	Operation     isOperation_Operation `protobuf_oneof:"operation"`
	Timestamp     int64                 `protobuf:"varint,100,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_okk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{7}
}

func (x *Operation) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Operation) GetAssertion() *Assertion {
	if x != nil {
		return x.Assertion
	}
	return nil
}

func (x *Operation) GetPrecondition() *Precondition {
	if x != nil {
		return x.Precondition
	}
	return nil
}

func (x *Operation) GetOperation() isOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Operation) GetPut() *OperationPut {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Operation) GetDelete() *OperationDelete {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Operation) GetGet() *OperationGet {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Operation) GetList() *OperationList {
	if x != nil {
		if x, ok := x.Operation.(*Operation_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Operation) GetScan() *OperationScan {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

func (x *Operation) GetSessionRestart() *OperationSessionRestart {
	if x != nil {
		if x, ok := x.Operation.(*Operation_SessionRestart); ok {
			return x.SessionRestart
		}
	}
	return nil
}

func (x *Operation) GetDeleteRange() *OperationDeleteRange {
	if x != nil {
		if x, ok := x.Operation.(*Operation_DeleteRange); ok {
			return x.DeleteRange
		}
	}
	return nil
}

func (x *Operation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type isOperation_Operation interface {
	isOperation_Operation()
}

type Operation_Put struct {
	Put *OperationPut `protobuf:"bytes,4,opt,name=put,proto3,oneof"`
}

type Operation_Delete struct {
	Delete *OperationDelete `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type Operation_Get struct {
	Get *OperationGet `protobuf:"bytes,6,opt,name=get,proto3,oneof"`
}

type Operation_List struct {
	List *OperationList `protobuf:"bytes,7,opt,name=list,proto3,oneof"`
}

type Operation_Scan struct {
	Scan *OperationScan `protobuf:"bytes,8,opt,name=scan,proto3,oneof"`
}

type Operation_SessionRestart struct {
	SessionRestart *OperationSessionRestart `protobuf:"bytes,9,opt,name=session_restart,json=sessionRestart,proto3,oneof"`
}

type Operation_DeleteRange struct {
	DeleteRange *OperationDeleteRange `protobuf:"bytes,10,opt,name=delete_range,json=deleteRange,proto3,oneof"`
}

func (*Operation_Put) isOperation_Operation() {}

func (*Operation_Delete) isOperation_Operation() {}

func (*Operation_Get) isOperation_Operation() {}

func (*Operation_List) isOperation_Operation() {}

func (*Operation_Scan) isOperation_Operation() {}

func (*Operation_SessionRestart) isOperation_Operation() {}

func (*Operation_DeleteRange) isOperation_Operation() {}

type Precondition struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WatchNotification      *bool                  `protobuf:"varint,1,opt,name=watch_notification,json=watchNotification,proto3,oneof" json:"watch_notification,omitempty"`
	BypassIfAssertKeyExist *bool                  `protobuf:"varint,2,opt,name=bypass_if_assert_key_exist,json=bypassIfAssertKeyExist,proto3,oneof" json:"bypass_if_assert_key_exist,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Precondition) Reset() {
	*x = Precondition{}
	mi := &file_okk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Precondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Precondition) ProtoMessage() {}

func (x *Precondition) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Precondition.ProtoReflect.Descriptor instead.
func (*Precondition) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{8}
}

func (x *Precondition) GetWatchNotification() bool {
	if x != nil && x.WatchNotification != nil {
		return *x.WatchNotification
	}
	return false
}

func (x *Precondition) GetBypassIfAssertKeyExist() bool {
	if x != nil && x.BypassIfAssertKeyExist != nil {
		return *x.BypassIfAssertKeyExist
	}
	return false
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NotificationType       `protobuf:"varint,1,opt,name=type,proto3,enum=io.oxia.okk.proto.v1.NotificationType" json:"type,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	KeyStart      *string                `protobuf:"bytes,3,opt,name=key_start,json=keyStart,proto3,oneof" json:"key_start,omitempty"`
	KeyEnd        *string                `protobuf:"bytes,4,opt,name=key_end,json=keyEnd,proto3,oneof" json:"key_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_okk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{9}
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_KEY_CREATED
}

func (x *Notification) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *Notification) GetKeyStart() string {
	if x != nil && x.KeyStart != nil {
		return *x.KeyStart
	}
	return ""
}

func (x *Notification) GetKeyEnd() string {
	if x != nil && x.KeyEnd != nil {
		return *x.KeyEnd
	}
	return ""
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_okk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{10}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Assertion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventuallyEmpty *bool                  `protobuf:"varint,1,opt,name=eventually_empty,json=eventuallyEmpty,proto3,oneof" json:"eventually_empty,omitempty"`
	EmptyRecords    *bool                  `protobuf:"varint,2,opt,name=empty_records,json=emptyRecords,proto3,oneof" json:"empty_records,omitempty"`
	PartitionKey    *string                `protobuf:"bytes,3,opt,name=partition_key,json=partitionKey,proto3,oneof" json:"partition_key,omitempty"`
	Records         []*Record              `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	Notification    *Notification          `protobuf:"bytes,5,opt,name=notification,proto3,oneof" json:"notification,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_okk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{11}
}

func (x *Assertion) GetEventuallyEmpty() bool {
	if x != nil && x.EventuallyEmpty != nil {
		return *x.EventuallyEmpty
	}
	return false
}

func (x *Assertion) GetEmptyRecords() bool {
	if x != nil && x.EmptyRecords != nil {
		return *x.EmptyRecords
	}
	return false
}

func (x *Assertion) GetPartitionKey() string {
	if x != nil && x.PartitionKey != nil {
		return *x.PartitionKey
	}
	return ""
}

func (x *Assertion) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Assertion) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ExecuteCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Testcase      string                 `protobuf:"bytes,1,opt,name=testcase,proto3" json:"testcase,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommand) Reset() {
	*x = ExecuteCommand{}
	mi := &file_okk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommand) ProtoMessage() {}

func (x *ExecuteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommand.ProtoReflect.Descriptor instead.
func (*ExecuteCommand) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteCommand) GetTestcase() string {
	if x != nil {
		return x.Testcase
	}
	return ""
}

func (x *ExecuteCommand) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ExecuteCommand) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=io.oxia.okk.proto.v1.Status" json:"status,omitempty"`
	StatusInfo    string                 `protobuf:"bytes,2,opt,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_okk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Ok
}

func (x *ExecuteResponse) GetStatusInfo() string {
	if x != nil {
		return x.StatusInfo
	}
	return ""
}

var File_okk_proto protoreflect.FileDescriptor

const file_okk_proto_rawDesc = "" +
	"\n" +
	"\tokk.proto\x12\x14io.oxia.okk.proto.v1\"\x19\n" +
	"\x17OperationSessionRestart\"\xbe\x01\n" +
	"\fOperationPut\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\tephemeral\x18\x03 \x01(\bR\tephemeral\x12(\n" +
	"\rpartition_key\x18\x04 \x01(\tH\x00R\fpartitionKey\x88\x01\x01\x12,\n" +
	"\x12sequence_key_delta\x18\x05 \x03(\x04R\x10sequenceKeyDeltaB\x10\n" +
	"\x0e_partition_key\"r\n" +
	"\fOperationGet\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12P\n" +
	"\x0fcomparison_type\x18\x02 \x01(\x0e2'.io.oxia.okk.proto.v1.KeyComparisonTypeR\x0ecomparisonType\"E\n" +
	"\rOperationList\x12\x1b\n" +
	"\tkey_start\x18\x01 \x01(\tR\bkeyStart\x12\x17\n" +
	"\akey_end\x18\x02 \x01(\tR\x06keyEnd\"E\n" +
	"\rOperationScan\x12\x1b\n" +
	"\tkey_start\x18\x01 \x01(\tR\bkeyStart\x12\x17\n" +
	"\akey_end\x18\x02 \x01(\tR\x06keyEnd\"#\n" +
	"\x0fOperationDelete\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"L\n" +
	"\x14OperationDeleteRange\x12\x1b\n" +
	"\tkey_start\x18\x01 \x01(\tR\bkeyStart\x12\x17\n" +
	"\akey_end\x18\x02 \x01(\tR\x06keyEnd\"\xd4\x05\n" +
	"\tOperation\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12B\n" +
	"\tassertion\x18\x02 \x01(\v2\x1f.io.oxia.okk.proto.v1.AssertionH\x01R\tassertion\x88\x01\x01\x12K\n" +
	"\fprecondition\x18\x03 \x01(\v2\".io.oxia.okk.proto.v1.PreconditionH\x02R\fprecondition\x88\x01\x01\x126\n" +
	"\x03put\x18\x04 \x01(\v2\".io.oxia.okk.proto.v1.OperationPutH\x00R\x03put\x12?\n" +
	"\x06delete\x18\x05 \x01(\v2%.io.oxia.okk.proto.v1.OperationDeleteH\x00R\x06delete\x126\n" +
	"\x03get\x18\x06 \x01(\v2\".io.oxia.okk.proto.v1.OperationGetH\x00R\x03get\x129\n" +
	"\x04list\x18\a \x01(\v2#.io.oxia.okk.proto.v1.OperationListH\x00R\x04list\x129\n" +
	"\x04scan\x18\b \x01(\v2#.io.oxia.okk.proto.v1.OperationScanH\x00R\x04scan\x12X\n" +
	"\x0fsession_restart\x18\t \x01(\v2-.io.oxia.okk.proto.v1.OperationSessionRestartH\x00R\x0esessionRestart\x12O\n" +
	"\fdelete_range\x18\n" +
	" \x01(\v2*.io.oxia.okk.proto.v1.OperationDeleteRangeH\x00R\vdeleteRange\x12\x1c\n" +
	"\ttimestamp\x18d \x01(\x03R\ttimestampB\v\n" +
	"\toperationB\f\n" +
	"\n" +
	"_assertionB\x0f\n" +
	"\r_precondition\"\xb9\x01\n" +
	"\fPrecondition\x122\n" +
	"\x12watch_notification\x18\x01 \x01(\bH\x00R\x11watchNotification\x88\x01\x01\x12?\n" +
	"\x1abypass_if_assert_key_exist\x18\x02 \x01(\bH\x01R\x16bypassIfAssertKeyExist\x88\x01\x01B\x15\n" +
	"\x13_watch_notificationB\x1d\n" +
	"\x1b_bypass_if_assert_key_exist\"\xc3\x01\n" +
	"\fNotification\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.io.oxia.okk.proto.v1.NotificationTypeR\x04type\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x00R\x03key\x88\x01\x01\x12 \n" +
	"\tkey_start\x18\x03 \x01(\tH\x01R\bkeyStart\x88\x01\x01\x12\x1c\n" +
	"\akey_end\x18\x04 \x01(\tH\x02R\x06keyEnd\x88\x01\x01B\x06\n" +
	"\x04_keyB\f\n" +
	"\n" +
	"_key_startB\n" +
	"\n" +
	"\b_key_end\"0\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xde\x02\n" +
	"\tAssertion\x12.\n" +
	"\x10eventually_empty\x18\x01 \x01(\bH\x00R\x0feventuallyEmpty\x88\x01\x01\x12(\n" +
	"\rempty_records\x18\x02 \x01(\bH\x01R\femptyRecords\x88\x01\x01\x12(\n" +
	"\rpartition_key\x18\x03 \x01(\tH\x02R\fpartitionKey\x88\x01\x01\x126\n" +
	"\arecords\x18\x04 \x03(\v2\x1c.io.oxia.okk.proto.v1.RecordR\arecords\x12K\n" +
	"\fnotification\x18\x05 \x01(\v2\".io.oxia.okk.proto.v1.NotificationH\x03R\fnotification\x88\x01\x01B\x13\n" +
	"\x11_eventually_emptyB\x10\n" +
	"\x0e_empty_recordsB\x10\n" +
	"\x0e_partition_keyB\x0f\n" +
	"\r_notification\"\x89\x01\n" +
	"\x0eExecuteCommand\x12\x1a\n" +
	"\btestcase\x18\x01 \x01(\tR\btestcase\x12=\n" +
	"\toperation\x18\x02 \x01(\v2\x1f.io.oxia.okk.proto.v1.OperationR\toperation\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"h\n" +
	"\x0fExecuteResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.io.oxia.okk.proto.v1.StatusR\x06status\x12\x1f\n" +
	"\vstatus_info\x18\x02 \x01(\tR\n" +
	"statusInfo*M\n" +
	"\x11KeyComparisonType\x12\t\n" +
	"\x05EQUAL\x10\x00\x12\t\n" +
	"\x05FLOOR\x10\x01\x12\v\n" +
	"\aCEILING\x10\x02\x12\t\n" +
	"\x05LOWER\x10\x03\x12\n" +
	"\n" +
	"\x06HIGHER\x10\x04*]\n" +
	"\x10NotificationType\x12\x0f\n" +
	"\vKEY_CREATED\x10\x00\x12\x10\n" +
	"\fKEY_MODIFIED\x10\x01\x12\x0f\n" +
	"\vKEY_DELETED\x10\x02\x12\x15\n" +
	"\x11KEY_RANGE_DELETED\x10\x03*U\n" +
	"\x06Status\x12\x06\n" +
	"\x02Ok\x10\x00\x12\x14\n" +
	"\x10AssertionFailure\x10\x01\x12\x14\n" +
	"\x10RetryableFailure\x10\x02\x12\x17\n" +
	"\x13NonRetryableFailure\x10\x032a\n" +
	"\x03Okk\x12Z\n" +
	"\aExecute\x12$.io.oxia.okk.proto.v1.ExecuteCommand\x1a%.io.oxia.okk.proto.v1.ExecuteResponse(\x010\x01B P\x01Z\x1cgithub.com/oxia-db/okk/protob\x06proto3"

var (
	file_okk_proto_rawDescOnce sync.Once
	file_okk_proto_rawDescData []byte
)

func file_okk_proto_rawDescGZIP() []byte {
	file_okk_proto_rawDescOnce.Do(func() {
		file_okk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_okk_proto_rawDesc), len(file_okk_proto_rawDesc)))
	})
	return file_okk_proto_rawDescData
}

var file_okk_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_okk_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_okk_proto_goTypes = []any{
	(KeyComparisonType)(0),          // 0: io.oxia.okk.proto.v1.KeyComparisonType
	(NotificationType)(0),           // 1: io.oxia.okk.proto.v1.NotificationType
	(Status)(0),                     // 2: io.oxia.okk.proto.v1.Status
	(*OperationSessionRestart)(nil), // 3: io.oxia.okk.proto.v1.OperationSessionRestart
	(*OperationPut)(nil),            // 4: io.oxia.okk.proto.v1.OperationPut
	(*OperationGet)(nil),            // 5: io.oxia.okk.proto.v1.OperationGet
	(*OperationList)(nil),           // 6: io.oxia.okk.proto.v1.OperationList
	(*OperationScan)(nil),           // 7: io.oxia.okk.proto.v1.OperationScan
	(*OperationDelete)(nil),         // 8: io.oxia.okk.proto.v1.OperationDelete
	(*OperationDeleteRange)(nil),    // 9: io.oxia.okk.proto.v1.OperationDeleteRange
	(*Operation)(nil),               // 10: io.oxia.okk.proto.v1.Operation
	(*Precondition)(nil),            // 11: io.oxia.okk.proto.v1.Precondition
	(*Notification)(nil),            // 12: io.oxia.okk.proto.v1.Notification
	(*Record)(nil),                  // 13: io.oxia.okk.proto.v1.Record
	(*Assertion)(nil),               // 14: io.oxia.okk.proto.v1.Assertion
	(*ExecuteCommand)(nil),          // 15: io.oxia.okk.proto.v1.ExecuteCommand
	(*ExecuteResponse)(nil),         // 16: io.oxia.okk.proto.v1.ExecuteResponse
}
var file_okk_proto_depIdxs = []int32{
	0,  // 0: io.oxia.okk.proto.v1.OperationGet.comparison_type:type_name -> io.oxia.okk.proto.v1.KeyComparisonType
	14, // 1: io.oxia.okk.proto.v1.Operation.assertion:type_name -> io.oxia.okk.proto.v1.Assertion
	11, // 2: io.oxia.okk.proto.v1.Operation.precondition:type_name -> io.oxia.okk.proto.v1.Precondition
	4,  // 3: io.oxia.okk.proto.v1.Operation.put:type_name -> io.oxia.okk.proto.v1.OperationPut
	8,  // 4: io.oxia.okk.proto.v1.Operation.delete:type_name -> io.oxia.okk.proto.v1.OperationDelete
	5,  // 5: io.oxia.okk.proto.v1.Operation.get:type_name -> io.oxia.okk.proto.v1.OperationGet
	6,  // 6: io.oxia.okk.proto.v1.Operation.list:type_name -> io.oxia.okk.proto.v1.OperationList
	7,  // 7: io.oxia.okk.proto.v1.Operation.scan:type_name -> io.oxia.okk.proto.v1.OperationScan
	3,  // 8: io.oxia.okk.proto.v1.Operation.session_restart:type_name -> io.oxia.okk.proto.v1.OperationSessionRestart
	9,  // 9: io.oxia.okk.proto.v1.Operation.delete_range:type_name -> io.oxia.okk.proto.v1.OperationDeleteRange
	1,  // 10: io.oxia.okk.proto.v1.Notification.type:type_name -> io.oxia.okk.proto.v1.NotificationType
	13, // 11: io.oxia.okk.proto.v1.Assertion.records:type_name -> io.oxia.okk.proto.v1.Record
	12, // 12: io.oxia.okk.proto.v1.Assertion.notification:type_name -> io.oxia.okk.proto.v1.Notification
	10, // 13: io.oxia.okk.proto.v1.ExecuteCommand.operation:type_name -> io.oxia.okk.proto.v1.Operation
	2,  // 14: io.oxia.okk.proto.v1.ExecuteResponse.status:type_name -> io.oxia.okk.proto.v1.Status
	15, // 15: io.oxia.okk.proto.v1.Okk.Execute:input_type -> io.oxia.okk.proto.v1.ExecuteCommand
	16, // 16: io.oxia.okk.proto.v1.Okk.Execute:output_type -> io.oxia.okk.proto.v1.ExecuteResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_okk_proto_init() }
func file_okk_proto_init() {
	if File_okk_proto != nil {
		return
	}
	file_okk_proto_msgTypes[1].OneofWrappers = []any{}
	file_okk_proto_msgTypes[7].OneofWrappers = []any{
		(*Operation_Put)(nil),
		(*Operation_Delete)(nil),
		(*Operation_Get)(nil),
		(*Operation_List)(nil),
		(*Operation_Scan)(nil),
		(*Operation_SessionRestart)(nil),
		(*Operation_DeleteRange)(nil),
	}
	file_okk_proto_msgTypes[8].OneofWrappers = []any{}
	file_okk_proto_msgTypes[9].OneofWrappers = []any{}
	file_okk_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_okk_proto_rawDesc), len(file_okk_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_okk_proto_goTypes,
		DependencyIndexes: file_okk_proto_depIdxs,
		EnumInfos:         file_okk_proto_enumTypes,
		MessageInfos:      file_okk_proto_msgTypes,
	}.Build()
	File_okk_proto = out.File
	file_okk_proto_goTypes = nil
	file_okk_proto_depIdxs = nil
}
