// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: okk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Okk_Execute_FullMethodName = "/io.oxia.okk.proto.v1.Okk/Execute"
)

// OkkClient is the client API for Okk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OkkClient interface {
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteCommand, ExecuteResponse], error)
}

type okkClient struct {
	cc grpc.ClientConnInterface
}

func NewOkkClient(cc grpc.ClientConnInterface) OkkClient {
	return &okkClient{cc}
}

func (c *okkClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteCommand, ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Okk_ServiceDesc.Streams[0], Okk_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteCommand, ExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Okk_ExecuteClient = grpc.BidiStreamingClient[ExecuteCommand, ExecuteResponse]

// OkkServer is the server API for Okk service.
// All implementations must embed UnimplementedOkkServer
// for forward compatibility.
type OkkServer interface {
	Execute(grpc.BidiStreamingServer[ExecuteCommand, ExecuteResponse]) error
	mustEmbedUnimplementedOkkServer()
}

// UnimplementedOkkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOkkServer struct{}

func (UnimplementedOkkServer) Execute(grpc.BidiStreamingServer[ExecuteCommand, ExecuteResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedOkkServer) mustEmbedUnimplementedOkkServer() {}
func (UnimplementedOkkServer) testEmbeddedByValue()             {}

// UnsafeOkkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OkkServer will
// result in compilation errors.
type UnsafeOkkServer interface {
	mustEmbedUnimplementedOkkServer()
}

func RegisterOkkServer(s grpc.ServiceRegistrar, srv OkkServer) {
	// If the following call panics, it indicates UnimplementedOkkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Okk_ServiceDesc, srv)
}

func _Okk_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OkkServer).Execute(&grpc.GenericServerStream[ExecuteCommand, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Okk_ExecuteServer = grpc.BidiStreamingServer[ExecuteCommand, ExecuteResponse]

// Okk_ServiceDesc is the grpc.ServiceDesc for Okk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Okk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.oxia.okk.proto.v1.Okk",
	HandlerType: (*OkkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _Okk_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "okk.proto",
}
