{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: okk-agent-secrets
  namespace: {{ include "okk.namespace" . }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.agent.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
